version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: legal_ai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legal_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legal_ai_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: legal_ai_redis
    ports:
      - "6379:6379"
    networks:
      - legal_ai_network
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legal_ai_api
    env_file:
      - ./backend/.env
    volumes:
      - ./rag_docs:/app/rag_docs
    networks:
      - legal_ai_network
    depends_on:
      - db
      - redis
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.dev.ai-jurist.ru`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"


  traefik:
    image: traefik:v2.10
    container_name: legal_ai_traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-lididrozdova@yandex.ru"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - legal_ai_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  legal_ai_network:
    driver: bridge
